name: Makefile CI

on:
  push:
    branches: [ master ]
    tags:
      - "v*.*.*"
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
    - uses: ocaml/setup-ocaml@v2
      with:
        opam-depext: false
        opam-pin: false
        ocaml-compiler: 4.08.x
    
    - run: |
        opam pin add hvsock.3.0.0 "https://github.com/djs55/ocaml-hvsock.git" -n
        opam pin add protocol-9p.2.0.2 "https://github.com/djs55/ocaml-9p.git" -n
        opam pin add protocol-9p-unix.2.0.2 "https://github.com/djs55/ocaml-9p.git" -n 
        opam pin add vpnkit . -n
        opam install vpnkit alcotest ounit -y
    
    - run: opam exec -- dune build vpnkit.exe --profile release
    
    - name: Upload Archive
      uses: actions/upload-artifact@v2
      with:
        name: artifacts
        path: ./_build/**/*
      
  release:
    runs-on: ubuntu-latest

    needs: build
    if: startsWith(github.ref, 'refs/tags/')

    steps:
    - name: Download a single artifact
      uses: actions/download-artifact@v2
      with:
        name: artifacts
    - name: Release
      uses: softprops/action-gh-release@v1
      with:
        files: default/*.exe
